### PR TITLE
fix: fixed webkit intersection observer race condt

### LINKED ISSUE #1066: Investigate loading issues on IOS
## Context

It is observed that the app doesn't load properly on ios, specifically chrome. Taking minutes to load icons and then becoming unresponsive

Investigate and come back with resolution steps

### PR DESCRIPTION
**Pull request by joel-medicala-yral**
closes https://github.com/dolr-ai/product-roadmap/issues/1066

### CODE REVIEW

File: ssr/src/page/src/scrolling_post_view.rs [hunk 1]
```diff
@@ -44,7 +44,7 @@ pub fn ScrollingPostView<F: Fn() -> V + Clone + 'static + Send + Sync, V>(
     queue_end: RwSignal<bool>,
     #[prop(optional, into)] overlay: Option<ViewFn>,
     threshold_trigger_fetch: usize,
-    #[prop(optional, into)] hard_refresh_target: RwSignal<String>,
```
Comment (komal-sai-yral) [inline ssr/src/page/src/scrolling_post_view.rs:47]: how are we handling this. since after 200 odd scrolls, we won't have any more video elems to update. hard refresh purpose was to again start from first (hacky since we dont have a straightforward way to reuse vidoe elems and customize leptos For according to our needs)

Comment (komal-sai-yral) [reply ssr/src/page/src/scrolling_post_view.rs:47]: as in ?

Comment (komal-sai-yral) [reply ssr/src/page/src/scrolling_post_view.rs:47]: > loop nhi karwa sakte kya? can try doing that

ya do try, For started behaving weirdly last time I tried.

Comment (komal-sai-yral) [reply ssr/src/page/src/scrolling_post_view.rs:47]: basically if we are able to crack this, even better since we can just maintain a simple list of 10-20 and keep reusing

**Comment by komal-sai-yral** [comment]
seems to be a bug in profile scroll. not sure due to new changes or before. can you pls check. if from before, can create a bug issue

**Review by komal-sai-yral — APPROVED** [review]
